language: ruby
notifications:
  webhooks: http://pulse.pivotallabs.com/projects/8c898a43-06e2-43d8-8648-e53b649dcec7/status
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: gvanhove@pivotal.io
  password:
    secure: XHV8QLoPq/55nluEhXq7VpqD3cUKDIUVY2jl4+DBPnAXYdKI8ssCyav87P7UYETpUE7Vw4S69GGhGFuuqoS6hv6yni61XoQJgnbkfTE0U6Su0LP04+74AcuHb+kAN37vQK+gYC8bmDM+xwwzklemB/34dFlmwIJkpWgSvMi8ae0n9U3Yd04ds9FCPNo/KcyWAvVI4gf+ASP7sHt8wAXp/FP045evT7rD0YBvPxOGh7E/c6yTgSjLPXrksNpW+uKgb5hVEAem6QTXsgX8Duxu9IePMZsRNbC9FlYFoGJRi6grrNEt/qFCNIo7HCEz1bJQ4HTvLmM+nHCVS9tAVxg2SWPWdPnBwf5zzWy/pxFntLXV/9HBP4NOX/vip43NXu5KtKjgY0DLKsFNwNWCk6aOByLFpVWTKLqgbaX8aNbpyxIU5n0Pe6SJiqFRO2jfJMMSzutM5zmydKrey7y8+WVe7pVrsJPEc3JjMdKe1LxgPc3g4YXyPEyd1+WVqjFpY8GqbyuA0J6nojxrKGpoLmtHjSG41y6lSEUwOCMiJrTtsi6HVLv0Mj7ZJRTSmzrNi0JiDHYdu91a9YC0W2Nv8V7xwO9v5wOyvNxwhyPV0onkRgAy4cZUKT19tFHO3nG6o64WHUukHskraACtfeXkRcuTfRRrZnkS10HSJxAvxEU6bVM=
  organization: slackersoft
  space: project-william
  on:
    repo: pivotal-mojo/william
env:
  global:
    secure: t22ZJgPf4sCYUaBHmFSKgMPmBbQEGztAHFUK3BwwqfKM7vJS7VUA+nUWVzW/kp5Z3zedntUzuxMMdaV7ZeKPC8KlPczX+3LFx56gFPrZ4M3YTJIGE6w1KgVUESL43D6RexuEdffAOn3qxfmlhQiwMJTCG0FTQGv2vcsbkC3qCL4eruiRtYOLLki1b8IQH5vjY4vD/Hx0g+RqVYgtOhx88M1dNLvbpKVaa0Ilc9dmoYO+nG0mrjLlsqpUMfsUGMkZzBg9w/8l3FL4XZc7mixhnGMMIGCGtpNDvvPYjSjnOTIh0aqwFIpmaZM34ccLQqr9fBQ4K7UWb/VmNtTyE/6WxOwWln83al81JBhKBj5L4ebSd8+2rUn+/qZzcoevwAPVNTN8aC5Vu2XmSNakWl6RwyuhCDIRKYrYAfQQ/X8++sOmTWtSW7/EJ3tHLKeFPAUaf1dKLop9P0Kfq/5syZXA+gVFnj5RhS/oCI8yQyDnVn3ahRY2nsdn8JNvbhqkp6qrbhfGwzXcjoTqs/SX9kS3tZhiQqpdwLZjqSKwvjse0sIqTj1eSXyQD8R+5XlfhleTu6Ny7IbzAQUj28y8GpshIMS+UhjoF9EXffw5R4QDkVhtR9qVFnv8LUKx0csKtliwrylpk3++Vb++1F9MLgbFPOMogDDc58uhQ9Nh+DQ9gwc=
after_deploy: curl -H "X-TrackerToken: $TRACKER_TOKEN" -X PUT http://www.pivotaltracker.com/services/v3/projects/1529909/stories/deliver_all_finished -d ""